output_root: '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/checkpoints/EAGLE'
pytorch_data_dir: '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/data' 
save_pytorch_data_dir: '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/data'

experiment_name: "cityscapes"
res: 320
batch_size: 8
num_workers: 8
run_picie: False
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

dino_patch_size: 8
dino_feat_type: "feat"
projection_type: "nonlinear"
model_type: "vit_base"
pretrained_weights: ~
dataset_name: "cityscapes"

model_paths:
#  - '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/checkpoints/STEGO_CUSTOM/checkpoints/STEGO_DINOv2_city_dim_100_2024-09-10/step1695-clust_acc81.69.ckpt'
# - '../checkpoints/EAGLE_COCO_ViTS8.ckpt'
#  - '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/checkpoints/EAGLE/checkpoints/cityscapes/cityscapes_Sep12_17-51-36_vit_base_cityscapes_EAGLE/epoch=01-step=00003290-test/cluster/acc=0.00.ckpt'
  - '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/checkpoints/EAGLE/EAGLE_Cityscapes_ViTB8.ckpt'

hydra:
  run:
    dir: "."
  output_subdir: ~