output_root: '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/checkpoints/EAGLE'
pytorch_data_dir: '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/data' 
save_pytorch_data_dir: '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/data'

experiment_name: "cityscapes"
res: 320
batch_size: 8
num_workers: 8
run_picie: False
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

dino_patch_size: 8
dino_feat_type: "feat"
projection_type: "nonlinear"
model_type: "vit_base"
pretrained_weights: ~
dataset_name: "cityscapes"

model_paths:
# - '../checkpoints/EAGLE_COCO_ViTS8.ckpt'
  - '/dss/dssmcmlfs01/pr74ze/pr74ze-dss-0001/ru25jan4/checkpoints/EAGLE/checkpoints/cityscapes/cityscapes_Sep12_13-23-10_vit_base_cityscapes_EAGLE/epoch=01-step=00003500-test/cluster/acc=0.00.ckpt'

hydra:
  run:
    dir: "."
  output_subdir: ~